#itsybitsy_m0

CFLAGS= -Wall -g -nostartfiles -O -DF_CPU=48000000UL -ffreestanding \
-DARDUINO=10819 -DARDUINO_ARCH_SAMD -DARDUINO_SAMD_ADAFRUIT \
-D__SAMD21G18A__ -DCRYSTALLESS -DADAFRUIT_ITSYBITSY_M0 -DARDUINO_SAMD_ZERO -DARM_MATH_CM0PLUS -DUSB_VID=0x239A -DUSB_PID=0x800F \
-DUSBCON -DUSB_CONFIG_POWER=100 "-DUSB_MANUFACTURER=\"Adafruit\"" "-DUSB_PRODUCT=\"ItsyBitsy M0 Express\""

