#itsybitsy_m4

CFLAGS= -Wall -g -nostartfiles  -DF_CPU=120000000UL -ffreestanding \
-DARDUINO=10819 -DARDUINO_ARCH_SAMD -DARDUINO_SAMD_ADAFRUIT -DADAFRUIT_ITSYBITSY_M4 \
-D__SAMD51G19A__ -D__SAMD51__ -DCRYSTALLESS -DADAFRUIT_ITSYBITSY_M4_EXPRESS -DARDUINO_SAMD_ZERO -DARM_MATH_CM0PLUS \
-DUSB_VID=0x239A -DUSB_PID=0x802B \
-DUSBCON -DUSB_CONFIG_POWER=100 "-DUSB_MANUFACTURER=\"Adafruit\"" "-DUSB_PRODUCT=\"ItsyBitsy M4\""

